[package]
name = "zanbil-build"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
build-rs = "0.3.1"
cc = "1.2.34"
fs_extra = "1.3.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.5"
walkdir = "2.5.0"
